[package]
name = "aw-fel"
version = "0.2.0"
authors = ["Razican <razican@protonmail.ch>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/Razican/aw-fel-rs"
documentation = "https://docs.rs/aw-fel/"
description = """
Library for dealing with Allwinner devices in FEL mode, in pure Rust.
"""
keywords = ["arm", "sunxi", "allwinner", "fel"]

[dependencies]
error-chain = "0.7"
libusb = "0.3"
byteorder = "0.5"

[features]
default = ["uboot"]
uboot = []
