(function() {var implementors = {};
implementors["aw_fel"] = [{text:"impl&lt;'h&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"aw_fel/struct.FelHandle.html\" title=\"struct aw_fel::FelHandle\">FelHandle</a>&lt;'h&gt;",synthetic:true,types:["aw_fel::FelHandle"]},{text:"impl&lt;'h&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"aw_fel/struct.UsbHandle.html\" title=\"struct aw_fel::UsbHandle\">UsbHandle</a>&lt;'h&gt;",synthetic:true,types:["aw_fel::UsbHandle"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"aw_fel/struct.Fel.html\" title=\"struct aw_fel::Fel\">Fel</a>",synthetic:true,types:["aw_fel::Fel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"aw_fel/enum.FelError.html\" title=\"enum aw_fel::FelError\">FelError</a>",synthetic:true,types:["aw_fel::FelError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"aw_fel/soc/struct.Version.html\" title=\"struct aw_fel::soc::Version\">Version</a>",synthetic:true,types:["aw_fel::soc::Version"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"aw_fel/soc/struct.SRAMSwapBuffers.html\" title=\"struct aw_fel::soc::SRAMSwapBuffers\">SRAMSwapBuffers</a>",synthetic:true,types:["aw_fel::soc::SRAMSwapBuffers"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"aw_fel/soc/struct.Info.html\" title=\"struct aw_fel::soc::Info\">Info</a>",synthetic:true,types:["aw_fel::soc::Info"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"aw_fel/uboot/enum.UbootImageType.html\" title=\"enum aw_fel::uboot::UbootImageType\">UbootImageType</a>",synthetic:true,types:[]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
